### ISSUE TITLE
Application Settings Doesnt Work

### ISSUE THREAD

**Issue by sadican** [MrMEEE/ironhide#115]
Hi,
I'm currently using Asus N61Jv and I installed ironhide. It works perfectly but I cant open Ironhide Application Settings. I tried to open it from terminal and NoOptionError traceback is listed.

sadican@sdcn:~$ sudo ironhide-app-settings --help
Using configuration file: /home/sadican/.ironhide-uirc
Traceback (most recent call last):
  File "/usr/bin/ironhide-app-settings", line 392, in <module>
    Appset = Applications_settings()
  File "/usr/bin/ironhide-app-settings", line 121, in **init**
    self.build_app_list()
  File "/usr/bin/ironhide-app-settings", line 220, in build_app_list  
    for app_info in self.file_set.get_apps_info():  
  File "/usr/share/ironhide-ui/app/DesktopFile.py", line 84, in get_apps_info
    app_config = desktop_file.get_app_config()
  File "/usr/share/ironhide-ui/app/DesktopFile.py", line 171, in get_app_config
    self.app_exec= self.config.get('Desktop Entry','Exec')
  File "/usr/lib/python2.7/ConfigParser.py", line 610, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'Exec' in section: 'Desktop Entry

**Comment by rockorequin** [comment]
See issue #77, the fix is a simple one (edit a line in /usr/share/ironhide-ui/apps/Config.py and another in /usr/bin/ironhide-indicator). I don't know why it isn't in the PPA yet.

**Comment by sadican** [comment]
Thanks but only changing Config.py is enough. In second file, that statement doesnt exist thus I only changed py file and it works like a charm, thanks again (:
