### ISSUE TITLE
ironhide-indicator crashes when reading wrong desktop file

### ISSUE THREAD

**Issue by abranches** [MrMEEE/ironhide#129]
Hello,

I installed ironhide by the ppa in Ubuntu 11.04. When going to "Configure apps" in the ironhide-indicator, it crashes with the exception:

<pre>Using configuration file: /home/pedro/.ironhide-uirc
Traceback (most recent call last):
  File "/usr/bin/ironhide-indicator", line 169, in app_configure
    Applications_settings(file_set=file_set)
  File "/usr/share/ironhide-ui/app/AppSettings.py", line 121, in __init__
    self.build_app_list()
  File "/usr/share/ironhide-ui/app/AppSettings.py", line 220, in build_app_list
    for app_info in self.file_set.get_apps_info():
  File "/usr/share/ironhide-ui/app/DesktopFile.py", line 84, in get_apps_info
    app_config = desktop_file.get_app_config()
  File "/usr/share/ironhide-ui/app/DesktopFile.py", line 171, in get_app_config
    self.app_exec= self.config.get('Desktop Entry','Exec')
  File "/usr/lib/python2.7/ConfigParser.py", line 610, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'Exec' in section: 'Desktop Entry'</pre>

I investigated the problem and found out that this happens because it tries to read a .desktop file that isn't executable(the ones that don't contain the Exec section), like the ~/examples.desktop file that comes by default with Ubuntu.

The solution is pretty simple.
Here's the updated code: http://codeviewer.org/view/code:1f7b

The diff result:

83,84d82
<           if not desktop_file.is_executable():
<               continue
131,133d128
< 
<   def is_executable(self):
<       return self.config.has_option('Desktop Entry', 'Exec')

**Comment by rockorequin** [comment]
Is this related to issue #77? The configuration is wrong in the PPA, but it's an easy fix and I'm not sure why the fix hasn't made it into the PPA.

**Comment by abranches** [comment]
Yes, it seams to be related. Ironhide is reading files that it shouldn't.

It also isn't a bad idea to check if the file is executable or not. It will avoid some problems in the future if the configuration files can be read from other directories.
