### ISSUE TITLE
ironhide-appsettings fails.

### ISSUE THREAD

**Issue by sunilkhatri** [MrMEEE/ironhide#47]
- When I run ironhide-appsettings, I get:
  
  ironhide-app-settings 
  Using configuration file: /home/sunil/.ironhide-uirc
  Traceback (most recent call last):
  File "/usr/bin/ironhide-app-settings", line 392, in <module>
    Appset = Applications_settings()  
  File "/usr/bin/ironhide-app-settings", line 121, in **init**
    self.build_app_list()
  File "/usr/bin/ironhide-app-settings", line 220, in build_app_list
    for app_info in self.file_set.get_apps_info():
  File "/usr/share/ironhide-ui/app/DesktopFile.py", line 84, in get_apps_info
    app_config = desktop_file.get_app_config()
  File "/usr/share/ironhide-ui/app/DesktopFile.py", line 171, in get_app_config
    self.app_exec= self.config.get('Desktop Entry','Exec')
  File "/usr/lib/python2.7/ConfigParser.py", line 610, in get
    raise NoOptionError(option, section)
  ConfigParser.NoOptionError: No option 'Exec' in section: 'Desktop Entry'
- My .ironhide-uirc file looks like

[Ironhide UI]
preferred_app = []
- If I run "configure apps" from the indicator gui, nothing happens.

Help! 
Thanks
Sunil

**Comment by fatihyucesoy** [comment]
I'm having the same problem
Ubuntu Version : 11.10 Beta 1

BR
Fatih

**Comment by bodypilot** [comment]
I can confirm this to.
When running ironhide-app-settings I get the same output as sunilkhatri. The "configure apps"from the indicator also doesn't work for me.

1.0-1~nattyubuntu33 (ironhide) on Ubuntu 11.04

Bodypilot

**Comment by beudbeud** [comment]
i have a same problem in xubuntu 11.10

**Comment by alexander-hagg** [comment]
I have the same problem on ubuntu 11.04 - Samsung RC530 S08.

**Comment by topaxi** [comment]
Got the same problem on ubuntu 10.10 Lenovo 4236P2G ThinkPad T420

**Comment by icb410** [comment]
Here's the Fix:

Remove "examples.desktop" in your home directory or rename it with a different extension (like .bak)

Now configuration works but indicator still crashes on after starting a program (correctly with optirun).  Error on command line is:

(ironhide-indicator:4926): libnotify-WARNING *_: you must call notify_init() before showing
*_
libnotify:ERROR:notification.c:568:notify_notification_show: code should not be reached
Aborted (core dumped)

**Comment by icb410** [comment]
Got the indicator working... see issue#44 for code to replace ironhide-indicator with.
